# Generated by Django 6.0.7 on 2026-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_section_capacity_section_shift'),
        ('schools', '0001_initial'),
        ('students', '0002_student_date_of_birth_student_gender_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('school', 'roll_number'), name='unique_student_roll_number_per_school'),
        ),
    ]
