# Generated by Django 6.0.7 on 2026-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classlevel_is_board_class'),
        ('schools', '0001_initial'),
        ('students', '0003_student_unique_student_roll_number_per_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='board_roll_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('board_roll_number', ''), _negated=True), fields=('school', 'board_roll_number'), name='unique_student_board_roll_number_per_school'),
        ),
    ]
