# Generated by Django 6.0.7 on 2026-07-30 09:29

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_family_and_enrollment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=students.models.student_profile_image_path),
        ),
    ]
