# Generated by Django 6.0.7 on 2026-08-12 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('students', '0006_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='families.family'),
        ),
    ]
