# Generated by Django 6.0.7 on 2026-08-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_unique_monthly_fee_and_student_fee'),
        ('funds', '0001_fund_and_invoice_type'),
        ('schools', '0002_school_timezone'),
        ('students', '0006_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='funds.fund'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('monthly_fee', 'Monthly fee'), ('fund', 'Fund')], default='monthly_fee', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'status'], name='fees_invoic_invoice_d6eda9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fund', 'status'], name='fees_invoic_fund_id_6987c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('fund__isnull', False), ('invoice_type', 'fund')), fields=('fund', 'student'), name='invoice_unique_fund_per_student'),
        ),
    ]
