# Generated by Django 6.0.7 on 2026-07-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('interested_class', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visited', 'Visited'), ('applied', 'Applied'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(default='pending', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admissions.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('met_with', models.CharField(blank=True, max_length=255)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='schools.school')),
            ],
        ),
    ]
