# Generated by Django 6.0.7 on 2026-08-12 07:33

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_map_interested_class_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='board_roll_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='family_lookup_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parent_occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=admissions.models.inquiry_profile_image_path),
        ),
    ]
