# Generated by Django 6.0.7 on 2026-07-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classlevel_is_board_class'),
        ('accounts', '0002_teacherprofile_employee_id_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, help_text='Subject specialties for this teacher. Section assignments are managed separately.', related_name='specialist_teachers', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('cnic', ''), _negated=True), fields=('school', 'cnic'), name='unique_teacher_cnic_per_school'),
        ),
    ]
