# Generated by Django 6.0.7 on 2026-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_employment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(choices=[('subject_teacher', 'Subject Teacher'), ('accountant', 'Accountant'), ('principal', 'Principal'), ('sports_teacher', 'Sports Teacher'), ('maid', 'Maid')], default='subject_teacher', max_length=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
