# Generated by Django 6.0.7 on 2026-07-30 09:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_designation_and_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=accounts.models.teacher_profile_image_path),
        ),
    ]
