# Generated by Django 6.0.7 on 2026-07-30 09:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
