# Generated by Django 6.0.7 on 2026-08-05 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_backfill_section_class_teachers'),
        ('accounts', '0006_user_profile_image'),
        ('exams', '0001_initial'),
        ('schools', '0002_school_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-starts_on', '-id']},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['student__roll_number', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('class_test', 'Class test'), ('midterm', 'Midterm'), ('final', 'Final')], default='midterm', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('published', 'Published')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='marked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='examsheet',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_sheets', to='exams.exam'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_type__in', ['midterm', 'final'])), fields=('school', 'academic_year', 'name'), name='exam_unique_term_name'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_type', 'class_test')), fields=('academic_year', 'section', 'subject', 'name'), name='exam_unique_class_test'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_sheets', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_sheets', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_sheets', to='schools.school'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_sheets', to='academics.section'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_sheets', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_sheets_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_sheets', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='mark',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='exams.marksheet'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.UniqueConstraint(fields=('exam', 'section', 'subject'), name='mark_sheet_unique_exam_section_subject'),
        ),
    ]
