# Generated by Django 6.0.7 on 2026-08-12 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_code', models.CharField(max_length=32)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='schools.school')),
            ],
            options={
                'ordering': ['family_code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('school', 'family_code'), name='families_unique_code_per_school')],
            },
        ),
    ]
