# Generated by Django 6.0.7 on 2026-08-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_schema_and_school_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['day_of_week', 'start_time', 'id']},
        ),
    ]
