# Generated by Django 6.0.7 on 2026-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.CharField(choices=[('mwf', 'MWF'), ('tthf', 'TTHF'), ('daily', 'Daily')], default='daily', max_length=10),
        ),
    ]
