# Generated by Django 6.0.7 on 2026-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_section_capacity_section_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlevel',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='classlevel',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
