# Generated by Django 6.0.7 on 2026-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_classlevel_options_classlevel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='is_board_class',
            field=models.BooleanField(default=False, help_text='When enabled, students in this class can have a board examination roll number.'),
        ),
    ]
