# Generated by Django 6.0.7 on 2026-07-30 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classlevel_is_board_class'),
        ('accounts', '0004_teacher_designation_and_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this section. A teacher may teach many sections.', related_name='teaching_sections', to='accounts.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Optional class incharge / class teacher for this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_sections', to='accounts.teacherprofile'),
        ),
    ]
