# Generated by Django 6.0.7 on 2026-07-30 08:28

from django.db import migrations


def add_class_teachers_to_section_rosters(apps, schema_editor):
    Section = apps.get_model("academics", "Section")
    through = Section.teachers.through
    rows = [
        through(section_id=section.id, teacherprofile_id=section.class_teacher_id)
        for section in Section.objects.exclude(class_teacher_id=None).iterator()
    ]
    through.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_section_teachers_m2m'),
    ]

    operations = [
        migrations.RunPython(add_class_teachers_to_section_rosters, noop_reverse),
    ]
